plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dolbyrouter'
    buildToolsVersion = "36.1.0"
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.dolbyrouter"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    // 仅编译期需要，运行时由 LSPosed 注入
    compileOnly 'de.robv.android.xposed:api:82'
}
